/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.fincatto.junit5;

import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.Tag;
import org.junit.jupiter.api.Test;

class LibraryTest {

    @Test
    @Tag("fast")
    void testFastMethod() {
        Assertions.assertTrue(new Library().fastMethod(), "Ihu!");
    }

    @Test
    @Tag("slow")
    void testSlowMethod() {
        Assertions.assertEquals("Yeahhh", new Library().slowMethod(), "Deu ruim, brow!");
    }

    @TestDatabase
    void testDatabaseMethod() throws InterruptedException {
        Assertions.assertEquals("DB", new Library().databaseMethod(), "Nao pode testar esse por padrao!");
    }
}
