/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.fincatto.junit5;

public class Library {

    public boolean fastMethod() {
        return true;
    }

    public String slowMethod() {
        return "Yeahhh";
    }

    public String databaseMethod() throws InterruptedException {
        Thread.sleep(10000);
        return "DB";
    }
}
